name: Build PAM backend image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: pam-sync-server

jobs:
  build-push:
    name: Build & push backend image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Scaleway Container Registry
        run: echo "${{ secrets.SCALEWAY_API_KEY }}" | docker login "${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}" -u nologin --password-stdin

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ secrets.CONTAINER_REGISTRY_ENDPOINT }}/${{ env.IMAGE_NAME }}:staging
